name: ping7

services:
  appserver:
    type: php:7.4
    webroot: drupal7/web
    build_as_root:
      - /app/.lando/build_as_root
    build:
      - /app/.lando/build
    run_as_root:
      - /app/.lando/run_as_root
    run:
      - /app/.lando/run
  mariadb:
    type: mariadb:10.6
  memcached:
    type: memcached:1.5.12
  redis:
    type: redis:6.0
  elasticsearch:
    # Use custom image for M1 compatibility.
    # settings.php has harcoded values therefore.
    type: compose
    services:
      image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.0"
      command: "/bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper"
      user: elasticsearch
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        discovery.type: "single-node"
        bootstrap.memory_lock: "true"
      ulimits:
        memlock:
          soft: "-1"
          hard: "-1"
  # solr
  # varnish

tooling:
  install:
    service: appserver
    cmd: /app/.lando/cmd-install
  test:
    service: appserver
    cmd:
      - php -d memory_limit=-1 /app/vendor/bin/phpunit
  scan:
    service: appserver
    cmd:
      - php -l _ping.php
      - php -l settings.php
      - phpcs -sp --report=full --runtime-set testVersion 7.4 --standard=Drupal,DrupalPractice,Security,PHPCompatibility,VariableAnalysis,WunderDrupal,WunderSecurity _ping.php settings.php
      - phpstan analyze --level=5 --autoload-file scan-autoload.php -- _ping.php settings.php
      - psalm

version: 3.6.2
